use tauri::{AppHandle, State};

use super::ssh::{auth_for_host, with_db};
use crate::audit::{AuditEvent, AuditState};
use crate::credentials::CredentialState;
use crate::db::host_keys;
use crate::db::hosts as host_repo;
use crate::db::DbState;
use crate::error::AppResult;
use crate::ssh::pty::{self, PtyOpenResult, PtyState};

/// Opens an interactive PTY session to a host. `session_id` is generated by
/// the frontend (it owns the tab lifecycle); data flows back via `pty:data`
/// events carrying that id.
#[tauri::command]
pub async fn pty_open(
    session_id: String,
    host_id: i64,
    cols: u32,
    rows: u32,
    app: AppHandle,
    state: State<'_, DbState>,
    cred_state: State<'_, CredentialState>,
    pty_state: State<'_, PtyState>,
    audit: State<'_, AuditState>,
    errlog: State<'_, crate::errlog::ErrLogState>,
) -> AppResult<PtyOpenResult> {
    let (host, keys) = with_db(&state, |conn| {
        let host = host_repo::get(conn, host_id)?;
        let keys = host_keys::list_for_endpoint(conn, &host.hostname, host.port)?;
        Ok((host, keys))
    })?;
    let auth = match auth_for_host(&host, &cred_state)? {
        Some(a) => a,
        None => return Ok(PtyOpenResult::NoCredentials),
    };
    let fingerprints = keys.iter().map(|k| k.fingerprint_sha256.clone()).collect();
    let result = pty::open(
        app,
        &pty_state,
        session_id,
        &host.hostname,
        host.port,
        &host.username,
        fingerprints,
        auth,
        cols.clamp(2, 1000),
        rows.clamp(2, 1000),
    )
    .await?;
    match &result {
        PtyOpenResult::Opened => {
            let _ = audit.append(&AuditEvent::PtyOpened {
                host_label: host.label,
                hostname: host.hostname,
                port: host.port,
            });
        }
        // Failures that toast also persist to the error log (D-055).
        PtyOpenResult::AuthFailed { message } => errlog.log(
            "pty_open",
            Some(&host.label),
            &format!("authentication failed — {message}"),
        ),
        PtyOpenResult::Unreachable { message } => errlog.log(
            "pty_open",
            Some(&host.label),
            &format!("unreachable — {message}"),
        ),
        PtyOpenResult::KeyMismatch { .. } => errlog.log(
            "pty_open",
            Some(&host.label),
            "host key mismatch — connection refused",
        ),
        _ => {}
    }
    Ok(result)
}

#[tauri::command]
pub fn pty_write(
    session_id: String,
    data: String,
    pty_state: State<'_, PtyState>,
) -> AppResult<()> {
    pty_state.write(&session_id, data.as_bytes())
}

#[tauri::command]
pub fn pty_resize(
    session_id: String,
    cols: u32,
    rows: u32,
    pty_state: State<'_, PtyState>,
) -> AppResult<()> {
    pty_state.resize(&session_id, cols.clamp(2, 1000), rows.clamp(2, 1000))
}

#[tauri::command]
pub fn pty_close(session_id: String, pty_state: State<'_, PtyState>) -> AppResult<()> {
    pty_state.close(&session_id)
}
