use tauri::{AppHandle, State};

use super::ssh::{auth_for_host, with_db};
use crate::audit::{AuditEvent, AuditState};
use crate::credentials::CredentialState;
use crate::db::host_keys;
use crate::db::hosts as host_repo;
use crate::db::DbState;
use crate::error::AppResult;
use crate::ssh::pty::{self, PtyOpenResult, PtyState};

/// Opens an interactive PTY session to a host. `session_id` is generated by
/// the frontend (it owns the tab lifecycle); data flows back via `pty:data`
/// events carrying that id.
#[tauri::command]
pub async fn pty_open(
    session_id: String,
    host_id: i64,
    cols: u32,
    rows: u32,
    app: AppHandle,
    state: State<'_, DbState>,
    cred_state: State<'_, CredentialState>,
    pty_state: State<'_, PtyState>,
    audit: State<'_, AuditState>,
    errlog: State<'_, crate::errlog::ErrLogState>,
) -> AppResult<PtyOpenResult> {
    let (host, keys) = with_db(&state, |conn| {
        let host = host_repo::get(conn, host_id)?;
        let keys = host_keys::list_for_endpoint(conn, &host.hostname, host.port)?;
        Ok((host, keys))
    })?;
    let auth = match auth_for_host(&host, &cred_state)? {
        Some(a) => a,
        None => {
            // D-055 amendment (2026-06-13): no-credentials is a logged failure.
            errlog.log(
                "pty_open",
                Some(host.id),
                Some(&host.label),
                "no credentials stored",
            );
            return Ok(PtyOpenResult::NoCredentials);
        }
    };
    let fingerprints = keys.iter().map(|k| k.fingerprint_sha256.clone()).collect();
    let result = pty::open(
        app,
        &pty_state,
        session_id,
        &host.hostname,
        host.port,
        &host.username,
        fingerprints,
        auth,
        cols.clamp(2, 1000),
        rows.clamp(2, 1000),
    )
    .await?;
    match &result {
        PtyOpenResult::Opened => {
            let _ = audit.append(&AuditEvent::PtyOpened {
                host_label: host.label,
                hostname: host.hostname,
                port: host.port,
            });
        }
        // Failures that toast also persist to the error log (D-055).
        PtyOpenResult::AuthFailed { message } => errlog.log(
            "pty_open",
            Some(host.id),
            Some(&host.label),
            &format!("authentication failed — {message}"),
        ),
        PtyOpenResult::Unreachable { message } => errlog.log(
            "pty_open",
            Some(host.id),
            Some(&host.label),
            &format!("unreachable — {message}"),
        ),
        PtyOpenResult::KeyMismatch { .. } => errlog.log(
            "pty_open",
            Some(host.id),
            Some(&host.label),
            "host key mismatch — connection refused",
        ),
        _ => {}
    }
    Ok(result)
}

#[tauri::command]
pub fn pty_write(
    session_id: String,
    data: String,
    pty_state: State<'_, PtyState>,
) -> AppResult<()> {
    pty_state.write(&session_id, data.as_bytes())
}

#[tauri::command]
pub fn pty_resize(
    session_id: String,
    cols: u32,
    rows: u32,
    pty_state: State<'_, PtyState>,
) -> AppResult<()> {
    pty_state.resize(&session_id, cols.clamp(2, 1000), rows.clamp(2, 1000))
}

#[tauri::command]
pub fn pty_close(session_id: String, pty_state: State<'_, PtyState>) -> AppResult<()> {
    pty_state.close(&session_id)
}

/// Records one PTY-broadcast dispatch run for the persistent history (D-059).
/// Also records the command in the shared recall history so Up/Down works the
/// same as on the Broadcast tab.
#[tauri::command]
pub fn pty_history_add(
    run_id: String,
    ts: String,
    command: String,
    results: Vec<crate::db::pty_history::DispatchInput>,
    state: State<'_, DbState>,
) -> AppResult<()> {
    // Record the targeted sessions for the history view's tinting (D-061 sub-4),
    // with host ids so they tint by the host's live colour.
    let hist_hosts: Vec<crate::db::history::HistoryHost> = results
        .iter()
        .map(|r| crate::db::history::HistoryHost {
            id: r.host_id,
            label: r.label.clone(),
        })
        .collect();
    with_db(&state, |conn| {
        crate::db::pty_history::add_run(conn, &run_id, &ts, &command, &results)?;
        // Never block on the recall-history write (same rule as Broadcast).
        let _ = crate::db::history::add(conn, &command, &hist_hosts, "ptybroadcast");
        Ok(())
    })
}

/// Records an OmniTerminal dispatch in the shared command history (D-061
/// sub-4). Rendered as `OmniTerminal <hosts> <command>` with the hosts tinted
/// by their live colour. Never blocks the dispatch (best-effort).
#[tauri::command]
pub fn omni_log_command(
    command: String,
    hosts: Vec<crate::db::history::HistoryHost>,
    state: State<'_, DbState>,
) -> AppResult<()> {
    with_db(&state, |conn| {
        crate::db::history::add(conn, &command, &hosts, "omniterminal")
    })
}

/// Persists one displayed OmniTerminal block so the aggregate view survives
/// restarts (D-061 follow-up).
#[tauri::command]
pub fn omni_blocks_add(
    block: crate::db::omni_history::OmniBlockInput,
    state: State<'_, DbState>,
) -> AppResult<()> {
    with_db(&state, |conn| crate::db::omni_history::add(conn, &block))
}

/// The persisted OmniTerminal block log, oldest first.
#[tauri::command]
pub fn omni_blocks_list(
    limit: usize,
    state: State<'_, DbState>,
) -> AppResult<Vec<crate::db::omni_history::StoredOmniBlock>> {
    with_db(&state, |conn| {
        crate::db::omni_history::list(conn, limit.clamp(1, 5000))
    })
}

/// Clears the persisted OmniTerminal block log. Returns rows removed.
#[tauri::command]
pub fn omni_blocks_clear(state: State<'_, DbState>) -> AppResult<usize> {
    with_db(&state, |conn| crate::db::omni_history::clear(conn))
}

#[tauri::command]
pub fn pty_history_list(
    max_runs: usize,
    state: State<'_, DbState>,
) -> AppResult<Vec<crate::db::pty_history::StoredPtyRun>> {
    with_db(&state, |conn| {
        crate::db::pty_history::list(conn, max_runs.clamp(1, 1000))
    })
}

#[tauri::command]
pub fn pty_history_clear(state: State<'_, DbState>) -> AppResult<usize> {
    with_db(&state, |conn| crate::db::pty_history::clear(conn))
}
